server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?characterEncoding=utf-8&useSSL=false
    username: root
    password: qazwsxedcrfv123..3

rocketmq:
  name-server: 192.168.40.66:9876;192.168.40.40:9876
  producer:
    group: springBootProducerGroup